"""add trivia question table

Revision ID: 5093fc761dde
Revises: d0ad7b1f14ea
Create Date: 2025-11-08 12:07:11.698915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5093fc761dde'
down_revision: Union[str, Sequence[str], None] = 'd0ad7b1f14ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trivia_question_id'), 'trivia_question', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trivia_question_id'), table_name='trivia_question')
    op.drop_table('trivia_question')
    # ### end Alembic commands ###
