"""add whisper room table

Revision ID: c27f6e6e59b0
Revises: 5093fc761dde
Create Date: 2025-11-11 14:14:55.877304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27f6e6e59b0'
down_revision: Union[str, Sequence[str], None] = '5093fc761dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whisper_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_channel_id')
    )
    op.create_index(op.f('ix_whisper_room_id'), 'whisper_room', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whisper_room_id'), table_name='whisper_room')
    op.drop_table('whisper_room')
    # ### end Alembic commands ###
