"""add safari inventory

Revision ID: 6171c2763eef
Revises: 1d10f192935a
Create Date: 2025-10-28 16:09:00.677072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6171c2763eef'
down_revision: Union[str, Sequence[str], None] = '1d10f192935a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safari_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bait', sa.Integer(), nullable=False),
    sa.Column('pokeballs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_safari_inventory_id'), 'safari_inventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safari_inventory_id'), table_name='safari_inventory')
    op.drop_table('safari_inventory')
    # ### end Alembic commands ###
