"""fix tables

Revision ID: 6f179523868b
Revises: ab6f92c3528d
Create Date: 2025-10-28 15:21:39.758808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f179523868b'
down_revision: Union[str, Sequence[str], None] = 'ab6f92c3528d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'rarity',
               existing_type=postgresql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', name='rarity'),
               type_=sa.Enum('COMMON', 'UNCOMMON', 'RARY', 'LEGENDARY', name='rarity_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'rarity',
               existing_type=sa.Enum('COMMON', 'UNCOMMON', 'RARY', 'LEGENDARY', name='rarity_enum'),
               type_=postgresql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', name='rarity'),
               existing_nullable=False)
    # ### end Alembic commands ###
