"""add caught pokemon table

Revision ID: d0ad7b1f14ea
Revises: 6171c2763eef
Create Date: 2025-10-31 21:53:24.446816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ad7b1f14ea'
down_revision: Union[str, Sequence[str], None] = '6171c2763eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caught_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('caught_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caught_pokemon_id'), 'caught_pokemon', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caught_pokemon_id'), table_name='caught_pokemon')
    op.drop_table('caught_pokemon')
    # ### end Alembic commands ###
